services:
  - type: web
    name: scoreboard
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false 